### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by imNomanWaleed** [matiov/learn-BTs-with-GP#3]
When I click to access the video, ![image](https://github.com/matiov/learn-BTs-with-GP/assets/130292564/f8a3e5a7-dd97-4aae-811b-49bcb8d82c83)
I see this 
![image](https://github.com/matiov/learn-BTs-with-GP/assets/130292564/44e33f8a-271c-4cb2-9a85-81c2b4b10682)

Kindly fix it

**Comment by Royboy1998** [comment]
hey,I am also looking for how to implement this in Gazebo and finding that the video is not available. You have any update？

**Comment by matiov** [comment]
Hi.
The video should be downloadable from IEEE Xplore, where the peer-reviewed version of the paper is published.
Alternatively, please find it at this [link](https://www.youtube.com/watch?v=D_6YE3HhEnA), I have now updated the READMe.
For the Gazebo implementation, please send me an email and I will provide you with the link to it. You can find ways to reach me [here](https://matiov.github.io/)
